_target_: marsls_seg.utils.modules.segmentation.wrappers.IJEPA_SMP_Backbone

jepa_ckpt_path: data/ckpts/special/ijepa128-ft/ckpt_ep_200.pt
jepa_config_path: data/ckpts/special/ijepa128-ft/config.yaml
