_target_: marsls_seg.utils.modules.segmentation.wrappers.SSJEPA_SMP_Backbone

jepa_ckpt_path: data/ckpts/20260524-134501/ckpt_ep_150.pt
jepa_config_path: data/ckpts/20260524-134501/config.yaml
fusion_mlp_hidden_size: 3072
