_target_: marsls_seg.utils.modules.ssjepa.jepa.SpatioSpectralJEPA
sigreg_lambda: 0.02

encoder:
 
  _target_: marsls_seg.utils.modules.encoder.spatio_spectral_vit.SpatioSpectralVisionTransformer
  dim: 64
  patch_size: 8  
  n_heads: 4
  n_layers: 8
  img_size: 128
  n_channels: 7   
  n_groups: null

predictor:

  _target_: marsls_seg.utils.modules.jepa.extras.SimpleTransformerDecoderPredictor
  dim: ${model.encoder.dim}
  n_heads: ${model.encoder.n_heads}
  n_layers: 4
  n_groups: ${model.encoder.n_groups}

sigreg:
  _target_: marsls_seg.utils.modules.sigreg.SIGReg
  n_directions: 1024
  knots: 17