defaults:
  - _self_
  # - model: ijepa
  # - trainer: ijepa
  - model: segmentation
  - trainer: segmentation
  - data/processor: norm

data:
  root_dir: "data/marsls-seg/mmlsv2"
  params_file: "data/configs/mmls_norm.yaml"
  train_splits:
    - train
    - val
  eval_splits:
    - test

training:
  batch_size: 8
  lr: 3e-5
  num_workers: 0
  n_epochs: 500
  pin_memory: true
  # Evaluate model every ? epochs
  eval_int: 1
  # Save model ckpt every ? epochs
  save_int: 60
  # Where to save the model?
  ckpt_dir: data/ckpts

wandb:
  project: MarsLS-JEPA
  mode: "online"
  artifact_name: "marsls-ijepa"
  model_desc: ""
  group: ???
  run_name: ""
